# Generated by Django 3.1.7 on 2021-03-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='googlemap',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
