# Generated by Django 3.1.7 on 2021-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(null=True, upload_to='iconskill'),
        ),
    ]
