# Generated by Django 3.1.7 on 2021-02-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0002_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='titre',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
