# Generated by Django 3.1.7 on 2021-02-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0003_skill_titre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techno',
            new_name='Metier',
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'verbose_name': 'Metier', 'verbose_name_plural': 'Metiers'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='techno',
            new_name='metier',
        ),
    ]
