# Generated by Django 3.1.7 on 2021-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0004_auto_20210224_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='metier',
        ),
        migrations.AddField(
            model_name='skill',
            name='metier',
            field=models.ManyToManyField(related_name='skills', to='myservices.Metier'),
        ),
    ]
