# Generated by Django 3.1.7 on 2021-02-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0005_auto_20210224_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
