# Generated by Django 3.1.7 on 2021-03-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_add'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
