# Generated by Django 3.1.7 on 2021-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrealisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
