# Generated by Django 3.1.7 on 2021-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrealisations', '0002_portfolio_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
